<!DOCTYPE html>
<html>
    
    <head>
        <title>Lista de Empleados</title>
        <link rel="stylesheet" href="Content/bootstrap.min.css">
    </head>

    <body>

        <div class="container">

            <h2>Lista de Empleados</h2>
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                    <th>Name</th> 
                    <th>Email</th> 
                    <th>Position</th> 
                    <th>Salary</th> 
                    <th>Acción</th> 
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($empleados as $empleado): ?>
                        <tr>
                            <td><?php echo $empleado->name;?></td> 
                            <td><?php echo $empleado->email;?></td> 
                            <td><?php echo $empleado->position;?></td> 
                            <td><?php echo $empleado->salary;?></td> 
                            <td><a href="empleados/<?php echo $empleado->id; ?>">Ver detalle</a></td> 
                        </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </div> 
        

    </body>

</html>