<!DOCTYPE html>
<html>
    
    <head>
        <title>Detalle de Empleado</title>
        <link rel="stylesheet" href="../Content/bootstrap.min.css">
    </head>

    <body>
       
        <div class="container">
        
            <h2>Detalle de empleado <a class="pull-right" href="../empleados">atrás</a></h2>

            
            <div class="row">
                <div class="col-md-6">
                    <label>Name</label>
                    <input type="text" class="form-control input-sm" value="<?php echo $empleado->name?>" readonly>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-6">
                    <label>Email</label>
                    <input type="text" class="form-control input-sm" value="<?php echo $empleado->email?>" readonly>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-6">
                    <label>Phone</label>
                    <input type="text" class="form-control input-sm" value="<?php echo $empleado->phone?>" readonly>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-6">
                    <label>Address</label>
                    <input type="text" class="form-control input-sm" value="<?php echo $empleado->address?>" readonly>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-6">
                    <label>Position</label>
                    <input type="text" class="form-control input-sm" value="<?php echo $empleado->position?>" readonly>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-6">
                    <label>Salary</label>
                    <input type="text" class="form-control input-sm" value="<?php echo $empleado->salary?>" readonly>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-6">
                    <label>Skills</label>
                    
                    <ul>
                        <?php foreach($empleado->skills as $skill):?>
                            <li><?php echo $skill->skill;?></li>
                        <?php endforeach;?>
                    </ul>
                </div>
            </div>



        </div>

    </body>

</html>